// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpcd/deregister.proto

package grpcd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service deregistration request
type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_grpcd_deregister_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_deregister_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_grpcd_deregister_proto_rawDescGZIP(), []int{0}
}

// Service deregistration response
type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_grpcd_deregister_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_deregister_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_grpcd_deregister_proto_rawDescGZIP(), []int{1}
}

var File_grpcd_deregister_proto protoreflect.FileDescriptor

const file_grpcd_deregister_proto_rawDesc = "" +
	"\n" +
	"\x16grpcd/deregister.proto\x12\x05grpcd\"\x13\n" +
	"\x11DeregisterRequest\"\x14\n" +
	"\x12DeregisterResponseB/Z-git.sonicoriginal.software/grpcd-protos;grpcdb\x06proto3"

var (
	file_grpcd_deregister_proto_rawDescOnce sync.Once
	file_grpcd_deregister_proto_rawDescData []byte
)

func file_grpcd_deregister_proto_rawDescGZIP() []byte {
	file_grpcd_deregister_proto_rawDescOnce.Do(func() {
		file_grpcd_deregister_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcd_deregister_proto_rawDesc), len(file_grpcd_deregister_proto_rawDesc)))
	})
	return file_grpcd_deregister_proto_rawDescData
}

var file_grpcd_deregister_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcd_deregister_proto_goTypes = []any{
	(*DeregisterRequest)(nil),  // 0: grpcd.DeregisterRequest
	(*DeregisterResponse)(nil), // 1: grpcd.DeregisterResponse
}
var file_grpcd_deregister_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcd_deregister_proto_init() }
func file_grpcd_deregister_proto_init() {
	if File_grpcd_deregister_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcd_deregister_proto_rawDesc), len(file_grpcd_deregister_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcd_deregister_proto_goTypes,
		DependencyIndexes: file_grpcd_deregister_proto_depIdxs,
		MessageInfos:      file_grpcd_deregister_proto_msgTypes,
	}.Build()
	File_grpcd_deregister_proto = out.File
	file_grpcd_deregister_proto_goTypes = nil
	file_grpcd_deregister_proto_depIdxs = nil
}
