// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcd/discover.proto

package grpcd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Query for a method, and reports on the candidates it was answered with.
type DiscoverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Step:
	//
	//	*DiscoverRequest_MethodName
	//	*DiscoverRequest_DeadAddress
	Step          isDiscoverRequest_Step `protobuf_oneof:"step"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_grpcd_discover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_discover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_grpcd_discover_proto_rawDescGZIP(), []int{0}
}

func (x *DiscoverRequest) GetStep() isDiscoverRequest_Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *DiscoverRequest) GetMethodName() string {
	if x != nil {
		if x, ok := x.Step.(*DiscoverRequest_MethodName); ok {
			return x.MethodName
		}
	}
	return ""
}

func (x *DiscoverRequest) GetDeadAddress() string {
	if x != nil {
		if x, ok := x.Step.(*DiscoverRequest_DeadAddress); ok {
			return x.DeadAddress
		}
	}
	return ""
}

type isDiscoverRequest_Step interface {
	isDiscoverRequest_Step()
}

type DiscoverRequest_MethodName struct {
	// First message: the fully qualified method name
	// (e.g., "principal.PrincipalService.CreatePrincipal")
	MethodName string `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3,oneof"`
}

type DiscoverRequest_DeadAddress struct {
	// Subsequent messages: a candidate the client could not reach. grpcd
	// removes it and answers with another.
	DeadAddress string `protobuf:"bytes,2,opt,name=dead_address,json=deadAddress,proto3,oneof"`
}

func (*DiscoverRequest_MethodName) isDiscoverRequest_Step() {}

func (*DiscoverRequest_DeadAddress) isDiscoverRequest_Step() {}

type DiscoverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address of a service that handles the requested method
	// e.g., "10.0.1.10:50054"
	//
	// One candidate per message. A client that reaches it closes the stream; a
	// client that cannot reports it dead and is sent the next.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_grpcd_discover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_discover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_grpcd_discover_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_grpcd_discover_proto protoreflect.FileDescriptor

const file_grpcd_discover_proto_rawDesc = "" +
	"\n" +
	"\x14grpcd/discover.proto\x12\x05grpcd\"a\n" +
	"\x0fDiscoverRequest\x12!\n" +
	"\vmethod_name\x18\x01 \x01(\tH\x00R\n" +
	"methodName\x12#\n" +
	"\fdead_address\x18\x02 \x01(\tH\x00R\vdeadAddressB\x06\n" +
	"\x04step\",\n" +
	"\x10DiscoverResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddressB/Z-git.sonicoriginal.software/grpcd-protos;grpcdb\x06proto3"

var (
	file_grpcd_discover_proto_rawDescOnce sync.Once
	file_grpcd_discover_proto_rawDescData []byte
)

func file_grpcd_discover_proto_rawDescGZIP() []byte {
	file_grpcd_discover_proto_rawDescOnce.Do(func() {
		file_grpcd_discover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcd_discover_proto_rawDesc), len(file_grpcd_discover_proto_rawDesc)))
	})
	return file_grpcd_discover_proto_rawDescData
}

var file_grpcd_discover_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcd_discover_proto_goTypes = []any{
	(*DiscoverRequest)(nil),  // 0: grpcd.DiscoverRequest
	(*DiscoverResponse)(nil), // 1: grpcd.DiscoverResponse
}
var file_grpcd_discover_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcd_discover_proto_init() }
func file_grpcd_discover_proto_init() {
	if File_grpcd_discover_proto != nil {
		return
	}
	file_grpcd_discover_proto_msgTypes[0].OneofWrappers = []any{
		(*DiscoverRequest_MethodName)(nil),
		(*DiscoverRequest_DeadAddress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcd_discover_proto_rawDesc), len(file_grpcd_discover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcd_discover_proto_goTypes,
		DependencyIndexes: file_grpcd_discover_proto_depIdxs,
		MessageInfos:      file_grpcd_discover_proto_msgTypes,
	}.Build()
	File_grpcd_discover_proto = out.File
	file_grpcd_discover_proto_goTypes = nil
	file_grpcd_discover_proto_depIdxs = nil
}
