// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpcd/register.proto

package grpcd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Service registration request
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of fully qualified method names this service handles
	// e.g., ["principal.PrincipalService.GetPrincipal", "principal.PrincipalService.CreatePrincipal"]
	Methods       []string `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_grpcd_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_grpcd_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_grpcd_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_grpcd_register_proto_rawDescGZIP(), []int{1}
}

var File_grpcd_register_proto protoreflect.FileDescriptor

const file_grpcd_register_proto_rawDesc = "" +
	"\n" +
	"\x14grpcd/register.proto\x12\x05grpcd\"+\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\"\x12\n" +
	"\x10RegisterResponseB/Z-git.sonicoriginal.software/grpcd-protos;grpcdb\x06proto3"

var (
	file_grpcd_register_proto_rawDescOnce sync.Once
	file_grpcd_register_proto_rawDescData []byte
)

func file_grpcd_register_proto_rawDescGZIP() []byte {
	file_grpcd_register_proto_rawDescOnce.Do(func() {
		file_grpcd_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcd_register_proto_rawDesc), len(file_grpcd_register_proto_rawDesc)))
	})
	return file_grpcd_register_proto_rawDescData
}

var file_grpcd_register_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcd_register_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: grpcd.RegisterRequest
	(*RegisterResponse)(nil), // 1: grpcd.RegisterResponse
}
var file_grpcd_register_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcd_register_proto_init() }
func file_grpcd_register_proto_init() {
	if File_grpcd_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcd_register_proto_rawDesc), len(file_grpcd_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcd_register_proto_goTypes,
		DependencyIndexes: file_grpcd_register_proto_depIdxs,
		MessageInfos:      file_grpcd_register_proto_msgTypes,
	}.Build()
	File_grpcd_register_proto = out.File
	file_grpcd_register_proto_goTypes = nil
	file_grpcd_register_proto_depIdxs = nil
}
