// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: grpcd/service.proto

package grpcd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GRPCDService_Register_FullMethodName = "/grpcd.GRPCDService/Register"
	GRPCDService_Discover_FullMethodName = "/grpcd.GRPCDService/Discover"
	GRPCDService_Watch_FullMethodName    = "/grpcd.GRPCDService/Watch"
)

// GRPCDServiceClient is the client API for GRPCDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GRPCDService handles service registration and method discovery
type GRPCDServiceClient interface {
	// Register a service instance with its methods and hold the stream.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RegisterResponse], error)
	// Discover addresses for a method, one candidate at a time.
	Discover(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DiscoverRequest, DiscoverResponse], error)
	// Hold an address for a method and be told when to move to another.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
}

type gRPCDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCDServiceClient(cc grpc.ClientConnInterface) GRPCDServiceClient {
	return &gRPCDServiceClient{cc}
}

func (c *gRPCDServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RegisterResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCDService_ServiceDesc.Streams[0], GRPCDService_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RegisterRequest, RegisterResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCDService_RegisterClient = grpc.ServerStreamingClient[RegisterResponse]

func (c *gRPCDServiceClient) Discover(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DiscoverRequest, DiscoverResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCDService_ServiceDesc.Streams[1], GRPCDService_Discover_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DiscoverRequest, DiscoverResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCDService_DiscoverClient = grpc.BidiStreamingClient[DiscoverRequest, DiscoverResponse]

func (c *gRPCDServiceClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GRPCDService_ServiceDesc.Streams[2], GRPCDService_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCDService_WatchClient = grpc.ServerStreamingClient[WatchResponse]

// GRPCDServiceServer is the server API for GRPCDService service.
// All implementations must embed UnimplementedGRPCDServiceServer
// for forward compatibility.
//
// GRPCDService handles service registration and method discovery
type GRPCDServiceServer interface {
	// Register a service instance with its methods and hold the stream.
	Register(*RegisterRequest, grpc.ServerStreamingServer[RegisterResponse]) error
	// Discover addresses for a method, one candidate at a time.
	Discover(grpc.BidiStreamingServer[DiscoverRequest, DiscoverResponse]) error
	// Hold an address for a method and be told when to move to another.
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	mustEmbedUnimplementedGRPCDServiceServer()
}

// UnimplementedGRPCDServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGRPCDServiceServer struct{}

func (UnimplementedGRPCDServiceServer) Register(*RegisterRequest, grpc.ServerStreamingServer[RegisterResponse]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGRPCDServiceServer) Discover(grpc.BidiStreamingServer[DiscoverRequest, DiscoverResponse]) error {
	return status.Error(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedGRPCDServiceServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedGRPCDServiceServer) mustEmbedUnimplementedGRPCDServiceServer() {}
func (UnimplementedGRPCDServiceServer) testEmbeddedByValue()                      {}

// UnsafeGRPCDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCDServiceServer will
// result in compilation errors.
type UnsafeGRPCDServiceServer interface {
	mustEmbedUnimplementedGRPCDServiceServer()
}

func RegisterGRPCDServiceServer(s grpc.ServiceRegistrar, srv GRPCDServiceServer) {
	// If the following call panics, it indicates UnimplementedGRPCDServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GRPCDService_ServiceDesc, srv)
}

func _GRPCDService_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RegisterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCDServiceServer).Register(m, &grpc.GenericServerStream[RegisterRequest, RegisterResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCDService_RegisterServer = grpc.ServerStreamingServer[RegisterResponse]

func _GRPCDService_Discover_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GRPCDServiceServer).Discover(&grpc.GenericServerStream[DiscoverRequest, DiscoverResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCDService_DiscoverServer = grpc.BidiStreamingServer[DiscoverRequest, DiscoverResponse]

func _GRPCDService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GRPCDServiceServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GRPCDService_WatchServer = grpc.ServerStreamingServer[WatchResponse]

// GRPCDService_ServiceDesc is the grpc.ServiceDesc for GRPCDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcd.GRPCDService",
	HandlerType: (*GRPCDServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _GRPCDService_Register_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Discover",
			Handler:       _GRPCDService_Discover_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _GRPCDService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcd/service.proto",
}
