// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: grpcd/service.proto

package grpcd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_grpcd_service_proto protoreflect.FileDescriptor

const file_grpcd_service_proto_rawDesc = "" +
	"\n" +
	"\x13grpcd/service.proto\x12\x05grpcd\x1a\x16grpcd/deregister.proto\x1a\x14grpcd/discover.proto\x1a\x14grpcd/register.proto2\xcb\x01\n" +
	"\fGRPCDService\x12;\n" +
	"\bRegister\x12\x16.grpcd.RegisterRequest\x1a\x17.grpcd.RegisterResponse\x12A\n" +
	"\n" +
	"Deregister\x12\x18.grpcd.DeregisterRequest\x1a\x19.grpcd.DeregisterResponse\x12;\n" +
	"\bDiscover\x12\x16.grpcd.DiscoverRequest\x1a\x17.grpcd.DiscoverResponseB/Z-git.sonicoriginal.software/grpcd-protos;grpcdb\x06proto3"

var file_grpcd_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: grpcd.RegisterRequest
	(*DeregisterRequest)(nil),  // 1: grpcd.DeregisterRequest
	(*DiscoverRequest)(nil),    // 2: grpcd.DiscoverRequest
	(*RegisterResponse)(nil),   // 3: grpcd.RegisterResponse
	(*DeregisterResponse)(nil), // 4: grpcd.DeregisterResponse
	(*DiscoverResponse)(nil),   // 5: grpcd.DiscoverResponse
}
var file_grpcd_service_proto_depIdxs = []int32{
	0, // 0: grpcd.GRPCDService.Register:input_type -> grpcd.RegisterRequest
	1, // 1: grpcd.GRPCDService.Deregister:input_type -> grpcd.DeregisterRequest
	2, // 2: grpcd.GRPCDService.Discover:input_type -> grpcd.DiscoverRequest
	3, // 3: grpcd.GRPCDService.Register:output_type -> grpcd.RegisterResponse
	4, // 4: grpcd.GRPCDService.Deregister:output_type -> grpcd.DeregisterResponse
	5, // 5: grpcd.GRPCDService.Discover:output_type -> grpcd.DiscoverResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcd_service_proto_init() }
func file_grpcd_service_proto_init() {
	if File_grpcd_service_proto != nil {
		return
	}
	file_grpcd_deregister_proto_init()
	file_grpcd_discover_proto_init()
	file_grpcd_register_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcd_service_proto_rawDesc), len(file_grpcd_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcd_service_proto_goTypes,
		DependencyIndexes: file_grpcd_service_proto_depIdxs,
	}.Build()
	File_grpcd_service_proto = out.File
	file_grpcd_service_proto_goTypes = nil
	file_grpcd_service_proto_depIdxs = nil
}
