# https://taskfile.dev

version: "3"

silent: true

vars:
  GO_MODULE:
    sh: go -C go list -m

tasks:
  default: task --list-all

  gen-go:
    silent: false
    cmds:
      - 'echo "Generating code for go module: {{.GO_MODULE}}"'
      - |-
        protoc -Iprotos \
          --go_out=go --go_opt=paths=import --go_opt=module={{.GO_MODULE}} \
          --go-grpc_out=go --go-grpc_opt=paths=import --go-grpc_opt=module={{.GO_MODULE}} \
          protos/**/*.proto

  gen:
    silent: false
    cmds:
      - task: gen-go
