// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcd/watch.proto

package grpcd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Says which address the client holds for which method, and asks to be told
// when it should move.
type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The fully qualified method name the client discovered
	// (e.g., "/package.Service/Method").
	MethodName string `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// The address the client is connected to for it.
	Address       string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_grpcd_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_grpcd_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *WatchRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// An address the client should move to. Sent when a new address registers for
// the method, to a share of the clients holding other addresses, so the new
// replica takes its share without every client moving. The client probes it,
// moves, and opens a new Watch naming it.
type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_grpcd_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcd_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_grpcd_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_grpcd_watch_proto protoreflect.FileDescriptor

const file_grpcd_watch_proto_rawDesc = "" +
	"\n" +
	"\x11grpcd/watch.proto\x12\x05grpcd\"I\n" +
	"\fWatchRequest\x12\x1f\n" +
	"\vmethod_name\x18\x01 \x01(\tR\n" +
	"methodName\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\")\n" +
	"\rWatchResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddressB/Z-git.sonicoriginal.software/grpcd-protos;grpcdb\x06proto3"

var (
	file_grpcd_watch_proto_rawDescOnce sync.Once
	file_grpcd_watch_proto_rawDescData []byte
)

func file_grpcd_watch_proto_rawDescGZIP() []byte {
	file_grpcd_watch_proto_rawDescOnce.Do(func() {
		file_grpcd_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcd_watch_proto_rawDesc), len(file_grpcd_watch_proto_rawDesc)))
	})
	return file_grpcd_watch_proto_rawDescData
}

var file_grpcd_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcd_watch_proto_goTypes = []any{
	(*WatchRequest)(nil),  // 0: grpcd.WatchRequest
	(*WatchResponse)(nil), // 1: grpcd.WatchResponse
}
var file_grpcd_watch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcd_watch_proto_init() }
func file_grpcd_watch_proto_init() {
	if File_grpcd_watch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcd_watch_proto_rawDesc), len(file_grpcd_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcd_watch_proto_goTypes,
		DependencyIndexes: file_grpcd_watch_proto_depIdxs,
		MessageInfos:      file_grpcd_watch_proto_msgTypes,
	}.Build()
	File_grpcd_watch_proto = out.File
	file_grpcd_watch_proto_goTypes = nil
	file_grpcd_watch_proto_depIdxs = nil
}
