name: Tag and Release

on:
  workflow_dispatch:
    inputs:
      ecosystem:
        description: Ecosystem to be released
        required: true
        type: choice
        default: go
        options:
          - go
      version:
        description: Version to be released
        required: true
        default: 0.0.0
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v5
        with:
          ref: gen-${{ inputs.ecosystem }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Tag
        run: git tag ${{ inputs.ecosystem }}/v${{ inputs.version }}

      - name: Push Tag
        run: git push origin ${{ inputs.ecosystem }}/v${{ inputs.version }}
